language: python
sudo: false
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
notifications:
  email: false
